# Generated by Django 5.0.7 on 2024-08-18 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
