# Generated by Django 5.0.7 on 2024-10-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0006_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
