# Generated by Django 5.0.7 on 2024-10-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0004_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
