# Generated by Django 5.0.7 on 2024-11-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0011_clotheproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, choices=[('leva', 'Leva'), ('euro', 'Euro'), ('dollar', 'Dollar')], default='leva', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('o', 'Option O'), ('s', 'Option S')], default='o', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='price_other',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('negotiation', 'Negotiation')], default='negotiation', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
